### ISSUE TITLE
Update to Material Design

### ISSUE THREAD

**Issue by neomodern** [HenriDellal/emerald-dialer#10]
Ideally Material Design 2 for a nicer design.

**Comment by HenriDellal** [comment]
Hello.
It is most likely to not happen due to some reasons. The main reason is that Material Design apps require third-party libraries. It makes the building process for me harder because I write and build apps on my phone and can't use Gradle (it's very slow on ARM). Also, I'd like to keep the APK size rather low. Including material design libraries will increase the size drastically.

**Comment by neomodern** [comment]
Fair enough, I'd like to see a generally improved design then if that's possible so it doesn't have to be Material Design-based.

**Comment by HenriDellal** [comment]
I think that it needs animations on numpad toggling and probably better icons. I must be missing something.
