### ISSUE TITLE
Add gradle build files

### ISSUE THREAD

**Issue by prg318** [HenriDellal/emerald-dialer#16]
Hello,

Great work with this project so far.  However, I do not see any project files for opening and building the project easily in another IDE.  Would be great to provide project metadata files to allow for easier contributions

**Comment by HenriDellal** [comment]
Hello.
This project doesn't have any project files, because I develop apps with very basic IDE and add its files in .gitignore. It should be possible to import this project to Gradle though, just like it was done with Emerald Launcher, but I have to check if F-Droid can build the imported project without Gradle, and if it doesn't, to get known why it happens and fix it.

**Comment by prg318** [comment]
Thanks for the quick response.  Makes sense.  It would be very useful for users ans potential contributors to have a set of gradle build files checked into the git repository so anyone can build the application without much trouble.

(If I understand correctly, android-studio and other major IDEs for android can figure most everything out from the Gradle files themselves

Thanks again for your hard work on this and for releasing the source publicly!

**Comment by HenriDellal** [comment]
Solved.
