### ISSUE TITLE
Contacts button

### ISSUE THREAD

**Issue by ajvsol** [HenriDellal/emerald-dialer#18]
A button along the button which can open your default Contacts app would be helpful, or at least a setting to enable one.

**Comment by HenriDellal** [comment]
I'm not sure about this one. Honestly, can't find the best place for it.

**Comment by neomodern** [comment]
I imagined it reducing the width of the green call button, so it could be an icon next to the hamburger menu.

**Comment by sefernet** [comment]
+1 
Yes, please

**Comment by DJCrashdummy** [comment]
IMHO it is enough to open it via a chosen contact (like it is already possible), although it would be much better to open the chosen contact itself, not just the app!!!
because i don't get it why you would like to open the plain contacts-app via the dialer, just use its own launcher; but well... if the additional button it is just optional, it won't bother anyone.
