### ISSUE TITLE
crash apps 

### ISSUE THREAD

**Issue by Disqu3-mirOir-qt** [HenriDellal/emerald-dialer#23]
hi 

I received a call from a mask / private number

after this call the application did not want to start anymore it automatically close automatically

I had to delete the call log from another application to solve the problem

thank you

**Comment by sefernet** [comment]
Related #21

**Comment by puppykickr** [comment]
@Disqu3-mirOir-qt

Have the same issue.
Turns out the same if you accidently try to call out with airplane mode on.

Anyway, just deleting any calls that have no number attached solves the problem.

Now there actually is a reason for me to leave the stock dialer app enabled, just for that reason alone.

**Comment by ZarVladimirII** [comment]
It was kind of surprising when this happened to me too.
After the private number did leave the first 'page' of entries it did not crash any more. Thus, only when the private number entry should be displayed, but there is no phone number to show for emerald dialer.

It is really important to solve this issue. Thanks! Solution in #21 seems not to work, ohh it´s not released yet...
