### ISSUE TITLE
Double dialpad

### ISSUE THREAD

**Issue by JonnyTech** [HenriDellal/emerald-dialer#26]
Emerald dialer has its own dialpad. But if I click the field at the top of the dialer where the number appears then it shows my device input keypad.

![dialpad](https://user-images.githubusercontent.com/3584732/48666203-18bfc000-eab5-11e8-8911-b574a2951050.jpg)

**Comment by DJCrashdummy** [comment]
just for info: i can't confirm this for version 1.0.5 on a LineageOS 14.1 (based on AOSP 7.1.x).

**Comment by joeyLaus** [comment]
I am having the same issue here as @JonnyTech on Android 9.0 LineageOS

This only happens when you click in the "cursor field" next to the Plus sign.  Please remove the ability to click there so that the dialpad does not appear.

The App's dialpad should also be more square-ish. At the moment each button is very flat and low.. Please expand it horizontally for better appearance. Just like the default dialpad of LineageOS
